# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'What3Keywords' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for What3Keywords
    pod 'SnapKit', '~> 5.0.0'
    pod 'Then'

  target 'What3KeywordsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
